# Generated by Django 5.2.9 on 2025-12-29 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_game_black_time_game_last_move_timestamp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="bet_amount",
            field=models.DecimalField(
                decimal_places=18,
                default=0,
                help_text="Bet amount in ETH",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="claim_tx_hash",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="deposit_tx_hash",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="payout_claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="signature_r",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="signature_s",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="signature_v",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="ethereum_address",
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["is_active", "black_player"],
                name="main_game_is_acti_5a9d8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["created_at"], name="main_game_created_e826b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="move",
            index=models.Index(
                fields=["game", "move_number"], name="main_move_game_id_5ddf34_idx"
            ),
        ),
    ]
