# Generated by Django 5.2.9 on 2026-02-14 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_game_draw_offered_by_game_is_private_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="think_time_seconds",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("signature_generated", "signature_generated"),
                            (
                                "signature_generation_failed",
                                "signature_generation_failed",
                            ),
                            ("payout_marked_claimed", "payout_marked_claimed"),
                            ("payout_mark_failed", "payout_mark_failed"),
                            ("deposit_verified", "deposit_verified"),
                            ("deposit_verify_failed", "deposit_verify_failed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("status", models.CharField(default="ok", max_length=16)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="main_securi_event_t_ae3c4d_idx",
                    )
                ],
            },
        ),
    ]
