# Generated by Django 5.2.9 on 2026-03-20 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_move_think_time_seconds_securityevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("inviting", "inviting"),
                            ("locked", "locked"),
                            ("in_progress", "in_progress"),
                            ("reviewing", "reviewing"),
                            ("finalized", "finalized"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("round_robin", "round_robin"),
                            ("swiss", "swiss"),
                            ("single_elim", "single_elim"),
                            ("double_elim", "double_elim"),
                        ],
                        default="round_robin",
                        max_length=20,
                    ),
                ),
                ("games_per_pairing", models.PositiveIntegerField(default=1)),
                ("max_players", models.PositiveIntegerField(default=8)),
                ("min_players", models.PositiveIntegerField(default=2)),
                (
                    "entry_fee_eth",
                    models.DecimalField(decimal_places=18, default=0, max_digits=20),
                ),
                (
                    "total_prize_pool_eth",
                    models.DecimalField(decimal_places=18, default=0, max_digits=20),
                ),
                ("invite_only", models.BooleanField(default=True)),
                ("review_required", models.BooleanField(default=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("check_in_deadline", models.DateTimeField(blank=True, null=True)),
                ("review_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "escrow_contract_address",
                    models.CharField(blank=True, max_length=42, null=True),
                ),
                ("escrow_locked", models.BooleanField(default=False)),
                (
                    "settlement_tx_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("review_completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("declined", "declined"),
                            ("expired", "expired"),
                            ("revoked", "revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_invites_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="main.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "invited"),
                            ("accepted", "accepted"),
                            ("declined", "declined"),
                            ("checked_in", "checked_in"),
                            ("disqualified", "disqualified"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("deposit_verified", models.BooleanField(default=False)),
                (
                    "deposit_tx_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                ("points", models.FloatField(default=0.0)),
                ("buchholz", models.FloatField(default=0.0)),
                ("sonneborn_berger", models.FloatField(default=0.0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="main.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("board_number", models.PositiveIntegerField(default=1)),
                ("game_index", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "scheduled"),
                            ("active", "active"),
                            ("completed", "completed"),
                            ("forfeit", "forfeit"),
                            ("voided", "voided"),
                            ("flagged", "flagged"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("white_win", "white_win"),
                            ("black_win", "black_win"),
                            ("draw", "draw"),
                            ("forfeit_white", "forfeit_white"),
                            ("forfeit_black", "forfeit_black"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("suspicion_score", models.FloatField(default=0.0)),
                ("requires_manual_review", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_match",
                        to="main.game",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="main.tournament",
                    ),
                ),
                (
                    "black_participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_black",
                        to="main.tournamentparticipant",
                    ),
                ),
                (
                    "white_participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_white",
                        to="main.tournamentparticipant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=18, default=0, max_digits=20),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=18, default=0, max_digits=20),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=18, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("paid", "paid"),
                            ("withheld", "withheld"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payout_tx_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payouts",
                        to="main.tournamentparticipant",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="main.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("match", "match"),
                            ("participant", "participant"),
                            ("tournament", "tournament"),
                        ],
                        default="match",
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "approved"),
                            ("flagged", "flagged"),
                            ("disqualified", "disqualified"),
                            ("voided", "voided"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("finalized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_decisions",
                        to="main.tournamentmatch",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_decisions",
                        to="main.tournamentparticipant",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_decisions",
                        to="main.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["status", "format"], name="main_tourna_status_98f29c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["creator", "created_at"], name="main_tourna_creator_184245_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentinvite",
            index=models.Index(
                fields=["tournament", "status"], name="main_tourna_tournam_f6fce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentinvite",
            index=models.Index(
                fields=["invitee", "status"], name="main_tourna_invitee_0061b1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentinvite",
            constraint=models.UniqueConstraint(
                fields=("tournament", "invitee"), name="unique_tournament_invitee"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentparticipant",
            index=models.Index(
                fields=["tournament", "status"], name="main_tourna_tournam_779345_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentparticipant",
            index=models.Index(
                fields=["user", "status"], name="main_tourna_user_id_9efd21_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentparticipant",
            constraint=models.UniqueConstraint(
                fields=("tournament", "user"), name="unique_tournament_participant"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentmatch",
            index=models.Index(
                fields=["tournament", "round_number"],
                name="main_tourna_tournam_37049e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentmatch",
            index=models.Index(
                fields=["status", "review_status"], name="main_tourna_status_4693f5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentmatch",
            constraint=models.UniqueConstraint(
                fields=("tournament", "round_number", "board_number", "game_index"),
                name="unique_tournament_match_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentpayout",
            index=models.Index(
                fields=["tournament", "status"], name="main_tourna_tournam_718f16_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentpayout",
            constraint=models.UniqueConstraint(
                fields=("tournament", "rank"), name="unique_tournament_payout_rank"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentreviewdecision",
            index=models.Index(
                fields=["tournament", "scope"], name="main_tourna_tournam_d5a8d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentreviewdecision",
            index=models.Index(
                fields=["decision", "finalized_at"],
                name="main_tourna_decisio_de42f8_idx",
            ),
        ),
    ]
