# Generated by Django 5.2.9 on 2026-03-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_tournament_tournamentinvite_tournamentparticipant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="swiss_rounds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
